# NB: Dependency inference is not yet implemented for JVM targets depending on protobuf targets,
# and so this dependency must be specified explicitly.
#  see https://github.com/pantsbuild/pants/issues/14960
scala_sources(dependencies=["src/protobuf/simple_example"])
